### ISSUE TITLE
使用更简易的包配置形式

### ISSUE THREAD

**Issue by songhuangcn** [songhuangcn/dpm#4]
当前：

```
packages/default.yml
packages/PACKAGE/default.yml
packages/PACKAGE/tag-xxx.yml
```

打算换成：

```
packages/default.yml
packages/PACKAGE.yml
```

其中 PACKAGE.yml:

```yaml
.default: &default
  # ...
latest:
  <<: *default
tag1:
  <<: *default
  # ...
tag2:
  <<: *default
  # ...
```
